#!/usr/bin/env python3
"""Transform Windows API and DLL names for lazy loading.

Uses the bit-reversal and XOR-key transformation from helper.txt to obfuscate
DLL and procedure names, generating C byte arrays to be decrypted lazily at runtime.
"""

import argparse
from pathlib import Path
import sys

KEY = 0xA5  # 10100101


def reverse_bits(x: int) -> int:
    """Reverse the 8 bits of byte x."""
    x = ((x & 0xF0) >> 4) | ((x & 0x0F) << 4)
    x = ((x & 0xCC) >> 2) | ((x & 0x33) << 2)
    x = ((x & 0xAA) >> 1) | ((x & 0x55) << 1)
    return x


def transform(data: bytes) -> bytes:
    """Apply bit-reversal and XOR key transformation to data bytes.

    Because reverse_bits is an involution and KEY (0xA5) is a bit-palindrome,
    applying transform twice restores the original data:
        transform(transform(data)) == data
    """
    return bytes(reverse_bits(b) ^ KEY for b in data)


# Windows DLL and API names used in core/launcher/launcher_windows.c
DLL_NAMES = [
    ("kernel32", "kernel32.dll"),
    ("advapi32", "advapi32.dll"),
]

PROC_NAMES = [
    # kernel32 procedures
    "SetConsoleCtrlHandler",
    "Sleep",
    "GetModuleFileNameW",
    "CreateFileMappingW",
    "MapViewOfFile",
    "UnmapViewOfFile",
    "DuplicateHandle",
    "CloseHandle",
    "LocalFree",
    "CreateFileW",
    "GetFinalPathNameByHandleW",
    "GetVolumeInformationW",
    "GetFileInformationByHandle",
    "WideCharToMultiByte",
    "RemoveDirectoryW",
    "DeleteFileW",
    "FindFirstFileW",
    "FindNextFileW",
    "FindClose",
    "ReadFile",
    "WriteFile",
    "FlushFileBuffers",
    "GetTempPathW",
    "QueryPerformanceCounter",
    "GetCurrentProcessId",
    "CreateDirectoryW",
    "GetStdHandle",
    "InitializeProcThreadAttributeList",
    "UpdateProcThreadAttribute",
    "DeleteProcThreadAttributeList",
    "CreateJobObjectW",
    "SetInformationJobObject",
    "CreateProcessW",
    "AssignProcessToJobObject",
    "ResumeThread",
    "WaitForSingleObject",
    "GetExitCodeProcess",
    "TerminateProcess",
    "ExitProcess",
    # advapi32 procedures
    "OpenProcessToken",
    "GetTokenInformation",
    "ConvertSidToStringSidW",
    "ConvertStringSecurityDescriptorToSecurityDescriptorW",
]


def format_c_array(var_name: str, original_str: str) -> str:
    """Format a transformed string as a C static const uint8_t array."""
    transformed = transform(original_str.encode("ascii"))
    hex_bytes = ", ".join(f"0x{b:02x}" for b in transformed)
    return f"static const uint8_t transf_{var_name}[] = {{{hex_bytes}}};"


def generate_header_content() -> str:
    """Generate the full content of lazy_names.h."""
    lines = [
        "/* Auto-generated by transform_names.py. Do not edit directly. */",
        "#ifndef WW_LAZY_NAMES_H",
        "#define WW_LAZY_NAMES_H",
        "",
        "#include <stddef.h>",
        "#include <stdint.h>",
        "",
        "/* Transformed DLL names */",
    ]

    for var_name, original_name in DLL_NAMES:
        lines.append(format_c_array(var_name, original_name))

    lines.append("")
    lines.append("/* Transformed procedure names */")

    for proc_name in PROC_NAMES:
        lines.append(format_c_array(proc_name, proc_name))

    lines.append("")
    lines.append("#endif /* WW_LAZY_NAMES_H */")
    lines.append("")
    return "\n".join(lines)


def verify_names() -> bool:
    """Verify roundtrip transformation for all known names."""
    all_ok = True
    for _, original in DLL_NAMES:
        enc = transform(original.encode("ascii"))
        dec = transform(enc).decode("ascii")
        if dec != original:
            print(f"FAIL: DLL {original} != {dec}", file=sys.stderr)
            all_ok = False

    for original in PROC_NAMES:
        enc = transform(original.encode("ascii"))
        dec = transform(enc).decode("ascii")
        if dec != original:
            print(f"FAIL: Proc {original} != {dec}", file=sys.stderr)
            all_ok = False

    return all_ok


def main():
    parser = argparse.ArgumentParser(
        description="Transform Windows API and DLL names for lazy runtime loading."
    )
    parser.add_argument(
        "--output",
        "-o",
        type=Path,
        help="Path to output header file (default: core/launcher/lazy_names.h)",
    )
    parser.add_argument(
        "--stdout",
        action="store_true",
        help="Print generated C header content to stdout",
    )
    parser.add_argument(
        "--names",
        nargs="+",
        help="Transform specific names passed on command line",
    )
    parser.add_argument(
        "--verify",
        action="store_true",
        help="Verify round-trip transformation of all names",
    )

    args = parser.parse_args()

    if args.verify:
        if verify_names():
            print(f"All {len(DLL_NAMES) + len(PROC_NAMES)} names verified successfully.")
            return 0
        return 1

    if args.names:
        for name in args.names:
            print(format_c_array(name.replace(".", "_"), name))
        return 0

    header_content = generate_header_content()

    if args.stdout:
        sys.stdout.write(header_content)
        return 0

    repo_root = Path(__file__).resolve().parent.parent.parent.parent
    output_path = args.output or (repo_root / "core" / "launcher" / "lazy_names.h")
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(header_content, encoding="utf-8")
    try:
        import subprocess

        subprocess.run(["clang-format", "-i", "--style=file", str(output_path)], check=False)
    except FileNotFoundError:
        pass
    print(f"Wrote transformed names to {output_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main() or 0)
