# Explicit native registrations; included in dependency order by unittests/CMakeLists.txt.
if(TARGET HttpProxyClient)
  waterwall_add_native_executable(http_proxy_client_lifecycle_test SUPPORT SOURCES ${WATERWALL_UNIT_SOURCE_ROOT}/tunnels/http_proxy/http_proxy_client_lifecycle_test.c)
  target_link_libraries(http_proxy_client_lifecycle_test PRIVATE HttpProxyClient ww)
  add_dependencies(waterwall_unit_tests http_proxy_client_lifecycle_test)
  add_waterwall_unit_test(waterwall.http_proxy_client_lifecycle_unit http_proxy_client_lifecycle_test "unit;http;proxy;portable;lifetime")
  if(CMAKE_SYSTEM_NAME STREQUAL "Linux")
    waterwall_add_native_executable(http_proxy_client_dns_test SUPPORT SOURCES ${WATERWALL_UNIT_SOURCE_ROOT}/tunnels/http_proxy/http_proxy_client_lifecycle_test.c)
    target_compile_definitions(http_proxy_client_dns_test PRIVATE HPC_DNS_TEST=1)
    target_link_options(http_proxy_client_dns_test PRIVATE "-Wl,--wrap=lineResolveDomainServiceAsync" "-Wl,--wrap=nodemanagerCreateTunnelInstance")
    target_link_libraries(http_proxy_client_dns_test PRIVATE HttpProxyClient ww)
    add_dependencies(waterwall_unit_tests http_proxy_client_dns_test)
    add_waterwall_unit_test(waterwall.http_proxy_client_dns_unit http_proxy_client_dns_test "unit;http;proxy;dns;lifetime")
  endif()
  get_target_property(_hpc_sources HttpProxyClient SOURCES)
  list(TRANSFORM _hpc_sources PREPEND "${CMAKE_SOURCE_DIR}/tunnels/HttpProxyClient/")
  waterwall_add_native_executable(http_proxy_client_no_splice_test SUPPORT SOURCES ${WATERWALL_UNIT_SOURCE_ROOT}/tunnels/http_proxy/http_proxy_client_lifecycle_test.c ${_hpc_sources}
    ${CMAKE_SOURCE_DIR}/tunnels/Internals/HttpProxyCommon/src/parser.c)
  target_include_directories(http_proxy_client_no_splice_test PRIVATE
    ${CMAKE_SOURCE_DIR}/tunnels/HttpProxyClient/include ${CMAKE_SOURCE_DIR}/tunnels/HttpProxyClient/include/HttpProxyClient
    ${CMAKE_SOURCE_DIR}/tunnels/Internals/HttpProxyCommon/include)
  target_compile_definitions(http_proxy_client_no_splice_test PRIVATE WW_HAVE_SPLICE=0)
  target_link_libraries(http_proxy_client_no_splice_test PRIVATE DomainResolver ww)
  add_dependencies(waterwall_unit_tests http_proxy_client_no_splice_test)
  add_waterwall_unit_test(waterwall.http_proxy_client_no_splice_unit http_proxy_client_no_splice_test "unit;http;proxy;portable;lifetime")
endif()

if(TARGET HttpProxyCommon)
  waterwall_add_native_executable(http_proxy_common_parser_test SUPPORT SOURCES ${WATERWALL_UNIT_SOURCE_ROOT}/tunnels/http_proxy/http_proxy_common_parser_test.c)
  target_link_libraries(http_proxy_common_parser_test PRIVATE HttpProxyCommon ww)
  add_dependencies(waterwall_unit_tests http_proxy_common_parser_test)
  add_waterwall_unit_test(waterwall.http_proxy_common_parser_unit http_proxy_common_parser_test "unit;http;proxy;portable")
endif()

if(TARGET HttpProxyServer)
  waterwall_add_native_executable(http_proxy_server_parser_test SUPPORT SOURCES ${WATERWALL_UNIT_SOURCE_ROOT}/tunnels/http_proxy/http_proxy_server_parser_test.c)
  target_link_libraries(http_proxy_server_parser_test PRIVATE HttpProxyServer ww)
  add_dependencies(waterwall_unit_tests http_proxy_server_parser_test)
  add_waterwall_unit_test(waterwall.http_proxy_server_parser_unit http_proxy_server_parser_test "unit;http;proxy;portable")
  waterwall_add_native_executable(http_proxy_server_lifecycle_test SUPPORT SOURCES ${WATERWALL_UNIT_SOURCE_ROOT}/tunnels/http_proxy/http_proxy_server_lifecycle_test.c)
  target_link_libraries(http_proxy_server_lifecycle_test PRIVATE HttpProxyServer AuthenticationClient ww)
  if(CMAKE_SYSTEM_NAME STREQUAL "Linux")
    target_compile_definitions(http_proxy_server_lifecycle_test PRIVATE HPS_TRAILER_ALLOC_TEST=1)
    target_link_options(http_proxy_server_lifecycle_test PRIVATE "-Wl,--wrap=memoryAllocate" "-Wl,--wrap=memoryFree")
  endif()
  add_dependencies(waterwall_unit_tests http_proxy_server_lifecycle_test)
  add_waterwall_unit_test(waterwall.http_proxy_server_lifecycle_unit http_proxy_server_lifecycle_test "unit;http;proxy;portable;lifetime")
endif()

