# Explicit native registrations; included in dependency order by unittests/CMakeLists.txt.
if(TARGET ObfuscatorClient AND TARGET ObfuscatorServer)
  waterwall_add_native_executable(obfuscator_large_stream_test SOURCES ${WATERWALL_UNIT_SOURCE_ROOT}/tunnels/obfuscator/obfuscator_large_stream_test.c ${WATERWALL_LINE_FAILURE_WW_SOURCES})
  target_link_libraries(obfuscator_large_stream_test PRIVATE ObfuscatorClient ObfuscatorServer ww)
  target_link_options(obfuscator_large_stream_test PRIVATE ${WATERWALL_LINE_FAILURE_WRAPS})
  add_dependencies(waterwall_unit_tests obfuscator_large_stream_test)
  add_waterwall_unit_test(waterwall.obfuscator_large_stream_unit obfuscator_large_stream_test "unit;tunnels;obfuscator;framing")
endif()

foreach(side IN ITEMS Client Server)
  if(LINUX AND TARGET KeepAlive${side})
    string(TOLOWER "${side}" side_lower)
    set(target "keepalive${side_lower}_splice_test")
    waterwall_add_native_executable(${target} SOURCES ${WATERWALL_UNIT_SOURCE_ROOT}/tunnels/keepalive/keepalive_splice_test.c ${WATERWALL_LINE_FAILURE_WW_SOURCES})
    target_link_libraries(${target} PRIVATE KeepAlive${side} ww)
    target_link_options(${target} PRIVATE ${WATERWALL_LINE_FAILURE_WRAPS}
      "-Wl,--wrap=read" "-Wl,--wrap=splicestreamCreate" "-Wl,--wrap=bufferqueueReserveExtra")
    if(side STREQUAL "Server")
      target_compile_definitions(${target} PRIVATE TEST_KEEPALIVE_SERVER=1)
    endif()
    add_dependencies(waterwall_unit_tests ${target})
    add_waterwall_unit_test(waterwall.keepalive${side_lower}_splice_unit ${target} "unit;tunnels;keepalive;splice;framing;lifetime")

    set(target "keepalive${side_lower}_no_splice_test")
    waterwall_add_native_executable(${target} SOURCES ${WATERWALL_UNIT_SOURCE_ROOT}/tunnels/keepalive/keepalive_splice_test.c ${WATERWALL_LINE_FAILURE_WW_SOURCES})
    waterwall_line_failure_test_use_tunnel(${target} KeepAlive${side})
    target_compile_definitions(${target} PRIVATE WW_HAVE_SPLICE=0)
    if(side STREQUAL "Server")
      target_compile_definitions(${target} PRIVATE TEST_KEEPALIVE_SERVER=1)
    endif()
    target_link_libraries(${target} PRIVATE ww)
    target_link_options(${target} PRIVATE ${WATERWALL_LINE_FAILURE_WRAPS}
      "-Wl,--wrap=read" "-Wl,--wrap=splicestreamCreate" "-Wl,--wrap=bufferqueueReserveExtra")
    add_dependencies(waterwall_unit_tests ${target})
    add_waterwall_unit_test(waterwall.keepalive${side_lower}_no_splice_unit ${target} "unit;tunnels;keepalive;no-splice;framing;lifetime")
  endif()
endforeach()

if(TARGET Bgp4Client AND TARGET Bgp4Server)
  waterwall_add_native_executable(bgp4_large_stream_test SOURCES ${WATERWALL_UNIT_SOURCE_ROOT}/tunnels/bgp/bgp4_large_stream_test.c ${WATERWALL_LINE_FAILURE_WW_SOURCES})
  target_link_libraries(bgp4_large_stream_test PRIVATE Bgp4Client Bgp4Server ww)
  target_link_options(bgp4_large_stream_test PRIVATE ${WATERWALL_LINE_FAILURE_WRAPS})
  target_link_options(bgp4_large_stream_test PRIVATE
    "-Wl,--wrap=fastRand" "-Wl,--wrap=splicestreamCreate" "-Wl,--wrap=bufferqueueReserveExtra"
    "-Wl,--wrap=splice" "-Wl,--wrap=read")
  add_dependencies(waterwall_unit_tests bgp4_large_stream_test)
  add_waterwall_unit_test(waterwall.bgp4_large_stream_unit bgp4_large_stream_test "unit;tunnels;bgp4;framing")
  if(LINUX)
    foreach(side Client Server)
      add_library(bgp4_${side}_no_splice_objects OBJECT)
      waterwall_line_failure_test_use_tunnel(bgp4_${side}_no_splice_objects Bgp4${side})
      target_compile_definitions(bgp4_${side}_no_splice_objects PRIVATE WW_HAVE_SPLICE=0)
    endforeach()
    waterwall_add_native_executable(bgp4_no_splice_test SOURCES ${WATERWALL_UNIT_SOURCE_ROOT}/tunnels/bgp/bgp4_large_stream_test.c ${WATERWALL_LINE_FAILURE_WW_SOURCES}
      $<TARGET_OBJECTS:bgp4_Client_no_splice_objects> $<TARGET_OBJECTS:bgp4_Server_no_splice_objects>)
    target_compile_definitions(bgp4_no_splice_test PRIVATE WW_HAVE_SPLICE=0)
    target_link_libraries(bgp4_no_splice_test PRIVATE ww)
    target_link_options(bgp4_no_splice_test PRIVATE ${WATERWALL_LINE_FAILURE_WRAPS}
      "-Wl,--wrap=fastRand" "-Wl,--wrap=splicestreamCreate" "-Wl,--wrap=bufferqueueReserveExtra")
    add_dependencies(waterwall_unit_tests bgp4_no_splice_test)
    add_waterwall_unit_test(waterwall.bgp4_no_splice_unit bgp4_no_splice_test "unit;tunnels;bgp4;framing;no-splice")
  endif()
endif()

