#include "reverseclient_handshake.h"

#define REVERSECLIENT_HANDSHAKE_BYTES_16 \
    0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, \
    0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF

#define REVERSECLIENT_HANDSHAKE_BYTES_64 \
    REVERSECLIENT_HANDSHAKE_BYTES_16, REVERSECLIENT_HANDSHAKE_BYTES_16, \
    REVERSECLIENT_HANDSHAKE_BYTES_16, REVERSECLIENT_HANDSHAKE_BYTES_16

#define REVERSECLIENT_HANDSHAKE_BYTES_256 \
    REVERSECLIENT_HANDSHAKE_BYTES_64, REVERSECLIENT_HANDSHAKE_BYTES_64, \
    REVERSECLIENT_HANDSHAKE_BYTES_64, REVERSECLIENT_HANDSHAKE_BYTES_64

WW_EXPORT const uint8_t reverseclientHandshakeBytes[] = {
    REVERSECLIENT_HANDSHAKE_BYTES_256,
    REVERSECLIENT_HANDSHAKE_BYTES_256,
    REVERSECLIENT_HANDSHAKE_BYTES_64,
    REVERSECLIENT_HANDSHAKE_BYTES_64,
};

WW_EXPORT const uint32_t reverseclientHandshakeLength = (uint32_t) sizeof(reverseclientHandshakeBytes);

#undef REVERSECLIENT_HANDSHAKE_BYTES_256
#undef REVERSECLIENT_HANDSHAKE_BYTES_64
#undef REVERSECLIENT_HANDSHAKE_BYTES_16
