# CTest: waterwall.test_support_unit. Builds/runs the NDEBUG subprocess fixture
# in the shared native run boundary. Exact 0/1/2 exits, atexit policy, continued
# TEST_CHECK execution and bounded diagnostic/call-site checks decide the verdict.
# Each child keeps its five-second deadline and separate retained capture.
include("${CMAKE_CURRENT_LIST_DIR}/../cmake/NativeRun.cmake")
set(WW_RUN_BUILD_DIR "${SUPPORT_BUILD_DIR}")
set(WW_RUN_CONFIG "${SUPPORT_CONFIG}")
set(WW_RUN_NAME waterwall.test_support_unit)
set(WW_RUN_SOURCE_DIR "${SUPPORT_SOURCE_DIR}")
set(WW_RUN_FIXTURE_DIR "${CMAKE_CURRENT_LIST_DIR}/c")
ww_native_run_begin()
ww_native_run_build(test_support_regression)
foreach(mode IN ITEMS pass check exit quick int uint size pointer text bytes)
  ww_native_run_execute("${mode}" 5 "${SUPPORT_EXECUTABLE}" "${mode}")
  file(READ "${WW_RUN_DIR}/${mode}.stdout.log" stdout)
  file(READ "${WW_RUN_DIR}/${mode}.stderr.log" stderr)
  # Windows stdio uses CRLF; retain raw logs and compare the same text policy.
  string(REPLACE "\r\n" "\n" stdout "${stdout}")
  set(expected 1)
  if(mode STREQUAL "pass")
    set(expected 0)
  elseif(mode STREQUAL "check")
    set(expected 2)
  endif()
  if(NOT "${WW_RUN_CHILD_RESULT}" STREQUAL "${expected}")
    ww_native_run_dump("${mode}")
    message(FATAL_ERROR "${mode}: expected exact exit ${expected}, got ${WW_RUN_CHILD_RESULT}; artifacts: ${WW_RUN_DIR}")
  endif()
  if(mode STREQUAL "pass")
    continue()
  endif()
  if(NOT stderr MATCHES "FAIL \\[support fixture\\] .*support_regression(_aux)?\\.c:[0-9]+:")
    message(FATAL_ERROR "Missing case/call-site diagnostic: ${stderr}; artifacts: ${WW_RUN_DIR}")
  endif()
  if(mode STREQUAL "check")
    if(NOT stdout STREQUAL "continuation marker\n" OR NOT stderr MATCHES "deliberate nonfatal failure.*expected true, got false")
      message(FATAL_ERROR "Nonfatal check lost its diagnostic or continuation; artifacts: ${WW_RUN_DIR}")
    endif()
    continue()
  endif()
  if(mode STREQUAL "exit")
    if(NOT stdout STREQUAL "buffered stdout marker\natexit marker\n")
      message(FATAL_ERROR "exit policy did not flush/run atexit; artifacts: ${WW_RUN_DIR}")
    endif()
  elseif(NOT stdout STREQUAL "")
    message(FATAL_ERROR "_Exit policy ran atexit or flushed stdout; artifacts: ${WW_RUN_DIR}")
  endif()
  if(mode STREQUAL "exit" OR mode STREQUAL "quick")
    set(detail "support_regression_aux.c:[0-9]+: deliberate NDEBUG failure.*expected true, got false")
  elseif(mode STREQUAL "int")
    set(detail "expected 2, got -7")
  elseif(mode STREQUAL "uint")
    set(detail "expected 2, got [0-9]+")
  elseif(mode STREQUAL "size")
    set(detail "expected 2, got 9")
  elseif(mode STREQUAL "pointer")
    set(detail "pointer comparison.*expected .*, got .*")
  elseif(mode STREQUAL "text")
    set(detail "expected \"expected\", got \"actual\"")
  else()
    set(detail "first difference at offset 17 of 1024: expected 0x00, got 0xa5")
    string(LENGTH "${stderr}" diagnostic_length)
    if(diagnostic_length GREATER 512)
      message(FATAL_ERROR "Byte diagnostic was not bounded; artifacts: ${WW_RUN_DIR}")
    endif()
  endif()
  if(NOT stderr MATCHES "${detail}")
    message(FATAL_ERROR "Missing comparison detail: ${stderr}; artifacts: ${WW_RUN_DIR}")
  endif()
endforeach()
ww_native_run_finish(passed)
