# Explicit integration registrations; preserve namespace and family variants.
add_waterwall_integration_test(waterwall.disturber_passthrough disturber_passthrough)
add_waterwall_integration_test(waterwall.obfuscator_roundtrip obfuscator_roundtrip)
add_waterwall_integration_test(waterwall.obfuscator_tls_record_roundtrip obfuscator_tls_record_roundtrip)
add_waterwall_integration_test(waterwall.encryption_roundtrip encryption_roundtrip)
add_waterwall_integration_test(waterwall.encryption_small_frame_roundtrip encryption_small_frame_roundtrip)
add_waterwall_integration_test(waterwall.bgp4_roundtrip bgp4_roundtrip)
add_waterwall_integration_test(waterwall.bgp4_tcp_splice_roundtrip bgp4_tcp_splice_roundtrip)
set_tests_properties(waterwall.bgp4_tcp_splice_roundtrip PROPERTIES ENVIRONMENT "WATERWALL_TEST_SPLICE=true")
add_waterwall_integration_test(waterwall.bgp4_tcp_no_splice_roundtrip bgp4_tcp_splice_roundtrip)
set_tests_properties(waterwall.bgp4_tcp_no_splice_roundtrip PROPERTIES ENVIRONMENT "WATERWALL_TEST_SPLICE=false")
add_waterwall_integration_test(waterwall.keepalive_roundtrip keepalive_roundtrip)
if(TARGET StreamFragmenter AND CMAKE_SYSTEM_NAME STREQUAL "Linux" AND NOT CMAKE_CROSSCOMPILING)
  foreach(fragmenter_mode IN ITEMS counter timed)
    foreach(splice_mode IN ITEMS true false)
      foreach(wait_for_est IN ITEMS false true)
        set(fragmenter_case waterwall.streamfragmenter_${fragmenter_mode}_splice_${splice_mode})
        if(wait_for_est)
          string(APPEND fragmenter_case "_wait_est")
        endif()
        add_waterwall_isolated_test(${fragmenter_case}
          "${PYTHON3_EXECUTABLE}" "${CMAKE_CURRENT_SOURCE_DIR}/streamfragmenter_integration.py"
          "$<TARGET_FILE:${WATERWALL_TEST_TARGET}>" "${splice_mode}" "${fragmenter_mode}" "${wait_for_est}")
        set_tests_properties(${fragmenter_case} PROPERTIES TIMEOUT 60)
        add_waterwall_test_labels(${fragmenter_case} "integration" "tunnels")
      endforeach()
    endforeach()
  endforeach()
  foreach(splice_mode IN ITEMS true false)
    foreach(tls_case IN ITEMS roundtrip deadline pending)
      set(fragmenter_case waterwall.streamfragmenter_tls_${tls_case}_splice_${splice_mode})
      add_waterwall_isolated_test(${fragmenter_case}
        "${PYTHON3_EXECUTABLE}" "${CMAKE_CURRENT_SOURCE_DIR}/streamfragmenter_integration.py"
        "$<TARGET_FILE:${WATERWALL_TEST_TARGET}>" "${splice_mode}" "tls_${tls_case}")
      set_tests_properties(${fragmenter_case} PROPERTIES TIMEOUT 60)
      add_waterwall_test_labels(${fragmenter_case} "integration" "tunnels" "tls")
    endforeach()
  endforeach()
endif()
include("${CMAKE_SOURCE_DIR}/tests/cmake/integration/tls-reality.cmake")
