# Explicit integration registrations; preserve namespace and family variants.
add_waterwall_integration_test(waterwall.trojan_password_tcp_loopback trojan_password_tcp_loopback)
add_waterwall_integration_test(waterwall.trojan_local_password_router_tcp_loopback trojan_local_password_router_tcp_loopback)
add_waterwall_expected_failure_integration_test(
  waterwall.trojan_local_password_router_rejects_wrong_password
  trojan_local_password_router_rejects_wrong_password
  "received finish before full response verification"
)
add_waterwall_integration_test(waterwall.trojan_fallback_invalid_probe_tcp_loopback trojan_fallback_invalid_probe_tcp_loopback)
add_waterwall_integration_test(waterwall.trojan_sha224_dest_protocol_tcp_loopback trojan_sha224_dest_protocol_tcp_loopback)
add_waterwall_integration_test(waterwall.trojan_dest_context_domain_resolve_tcp_loopback trojan_dest_context_domain_resolve_tcp_loopback)
add_waterwall_integration_test(waterwall.trojan_password_udp_loopback trojan_password_udp_loopback)
add_waterwall_integration_test(waterwall.trojan_dest_protocol_udp_loopback trojan_dest_protocol_udp_loopback)
add_waterwall_integration_test(waterwall.vless_uuid_tcp_loopback vless_uuid_tcp_loopback)
add_waterwall_integration_test(waterwall.vless_uuid_domain_tcp_loopback vless_uuid_domain_tcp_loopback)
add_waterwall_integration_test(waterwall.vless_dest_context_domain_resolve_tcp_loopback vless_dest_context_domain_resolve_tcp_loopback)
add_waterwall_integration_test(waterwall.vless_local_username_router_tcp_loopback vless_local_username_router_tcp_loopback)
add_waterwall_expected_failure_integration_test(
  waterwall.vless_local_username_router_rejects_wrong_password
  vless_local_username_router_rejects_wrong_password
  "received finish before full response verification"
)
add_waterwall_integration_test(waterwall.vless_fallback_invalid_probe_tcp_loopback vless_fallback_invalid_probe_tcp_loopback)
add_waterwall_integration_test(waterwall.vless_uuid_udp_loopback vless_uuid_udp_loopback)
add_waterwall_integration_test(waterwall.vless_auth_tcp_loopback vless_auth_tcp_loopback)
add_waterwall_integration_test(waterwall.vless_auth_udp_loopback vless_auth_udp_loopback)
add_waterwall_integration_test(waterwall.softiplimiter_vless_tcp_loopback softiplimiter_vless_tcp_loopback)
add_waterwall_integration_test(waterwall.softiplimiter_trojan_tcp_loopback softiplimiter_trojan_tcp_loopback)
add_waterwall_probe_integration_test(waterwall.softiplimiter_vless_reject_distinct_ip_probe softiplimiter_vless_reject_distinct_ip_probe 10)
add_waterwall_integration_test(waterwall.softiplimiter_identification_failure_passthrough softiplimiter_identification_failure_passthrough)
add_waterwall_probe_integration_test(waterwall.softiplimiter_identification_failure_close_probe softiplimiter_identification_failure_close_probe 10)
add_waterwall_integration_test(waterwall.udp_over_tcp_roundtrip udp_over_tcp_roundtrip)
add_waterwall_integration_test(waterwall.tcp_over_udp_roundtrip tcp_over_udp_roundtrip)
add_waterwall_integration_test(waterwall.tcp_over_udp_fec_roundtrip tcp_over_udp_fec_roundtrip)
add_waterwall_integration_test(waterwall.tcp_over_udp_disturber_roundtrip tcp_over_udp_disturber_roundtrip)
add_waterwall_integration_test(waterwall.tcp_over_udp_fec_disturber_roundtrip tcp_over_udp_fec_disturber_roundtrip)
