# Explicit integration registrations; preserve namespace and family variants.
add_waterwall_integration_test(waterwall.wireguard_udpstateless_packet_roundtrip wireguard_udpstateless_packet_roundtrip)
add_waterwall_wireguard_cookie_test(waterwall.wireguard_cookie_overload_roundtrip wireguard_cookie_overload_roundtrip)
add_waterwall_packet_analysis_test(waterwall.packet_analysis_ping_roundtrip packet_analysis_ping_roundtrip)
add_waterwall_packet_analysis_test(waterwall.packet_analysis_disturber_loss packet_analysis_disturber_loss)
add_waterwall_packet_analysis_test(waterwall.packet_analysis_receiver_head_bridge packet_analysis_receiver_head_bridge)
add_waterwall_packet_analysis_test(waterwall.packet_analysis_all_protocols packet_analysis_all_protocols)
add_waterwall_packet_analysis_test(waterwall.packet_analysis_unexpected_protocol packet_analysis_unexpected_protocol)
