# Auto-build and execute one native test in an isolated build-tree directory.
# Inputs are explicit registration data; no generated state belongs in source.
foreach(required IN ITEMS TARGET EXECUTABLE BUILD_DIR NAME SOURCE_DIR FIXTURE_DIR)
  if(NOT DEFINED UNIT_TEST_${required} OR "${UNIT_TEST_${required}}" STREQUAL "")
    message(FATAL_ERROR "UNIT_TEST_${required} is required")
  endif()
endforeach()
set(WW_RUN_BUILD_DIR "${UNIT_TEST_BUILD_DIR}")
set(WW_RUN_CONFIG "${UNIT_TEST_CONFIG}")
set(WW_RUN_NAME "${UNIT_TEST_NAME}")
set(WW_RUN_SOURCE_DIR "${UNIT_TEST_SOURCE_DIR}")
set(WW_RUN_FIXTURE_DIR "${UNIT_TEST_FIXTURE_DIR}")
foreach(stage IN ITEMS LOCK BUILD)
  if(DEFINED UNIT_TEST_${stage}_TIMEOUT)
    set(WW_RUN_${stage}_TIMEOUT "${UNIT_TEST_${stage}_TIMEOUT}")
  endif()
endforeach()
if(NOT DEFINED UNIT_TEST_TIMEOUT)
  set(UNIT_TEST_TIMEOUT 120)
endif()

include("${CMAKE_CURRENT_LIST_DIR}/../cmake/NativeRun.cmake")
ww_native_run_begin()
ww_native_run_build("${UNIT_TEST_TARGET}")
if(NOT EXISTS "${UNIT_TEST_EXECUTABLE}")
  ww_native_run_finish("missing executable")
  message(FATAL_ERROR "Unit-test executable is missing after build: ${UNIT_TEST_EXECUTABLE}")
endif()
ww_native_run_execute(child "${UNIT_TEST_TIMEOUT}" "${UNIT_TEST_EXECUTABLE}" ${UNIT_TEST_ARGUMENTS})
if(DEFINED UNIT_TEST_RESULT_FILE)
  # Auxiliary Python callers use this receipt without buffering the artifact
  # announcement. Their CTest process can still return the original skip code.
  file(WRITE "${UNIT_TEST_RESULT_FILE}" "${WW_RUN_CHILD_RESULT}\n")
endif()
if(DEFINED UNIT_TEST_SKIP_CODE AND "${WW_RUN_CHILD_RESULT}" STREQUAL "${UNIT_TEST_SKIP_CODE}")
  ww_native_run_dump(child)
  ww_native_run_finish("skipped (exit ${WW_RUN_CHILD_RESULT})")
elseif(NOT "${WW_RUN_CHILD_RESULT}" STREQUAL "0")
  ww_native_run_dump(child)
  ww_native_run_finish("execution failed: ${WW_RUN_CHILD_RESULT}")
  message(FATAL_ERROR "${UNIT_TEST_TARGET} execution failed: ${WW_RUN_CHILD_RESULT}")
else()
  ww_native_run_finish(passed)
endif()
