# Exact-result runner: each case must exit numerically 1. Signals, assertions,
# setup errors and zero exits fail. The shared lock covers build and all cases.
foreach(required IN ITEMS TARGET EXECUTABLE BUILD_DIR CASES NAME SOURCE_DIR FIXTURE_DIR)
  if(NOT DEFINED ABORT_TEST_${required} OR "${ABORT_TEST_${required}}" STREQUAL "")
    message(FATAL_ERROR "ABORT_TEST_${required} is required")
  endif()
endforeach()
set(WW_RUN_BUILD_DIR "${ABORT_TEST_BUILD_DIR}")
set(WW_RUN_CONFIG "${ABORT_TEST_CONFIG}")
set(WW_RUN_NAME "${ABORT_TEST_NAME}")
set(WW_RUN_SOURCE_DIR "${ABORT_TEST_SOURCE_DIR}")
set(WW_RUN_FIXTURE_DIR "${ABORT_TEST_FIXTURE_DIR}")
include("${CMAKE_CURRENT_LIST_DIR}/../cmake/NativeRun.cmake")
ww_native_run_begin()
ww_native_run_build("${ABORT_TEST_TARGET}")
if(NOT EXISTS "${ABORT_TEST_EXECUTABLE}")
  ww_native_run_finish("missing executable")
  message(FATAL_ERROR "Abort runtime executable is missing after build: ${ABORT_TEST_EXECUTABLE}")
endif()
string(REPLACE "|" ";" abort_cases "${ABORT_TEST_CASES}")
# Preserve the suite's original 120-second execution allowance across its cases.
string(TIMESTAMP execution_start "%s" UTC)
foreach(case_name IN LISTS abort_cases)
  string(TIMESTAMP execution_now "%s" UTC)
  math(EXPR remaining "120 - (${execution_now} - ${execution_start})")
  if(remaining LESS_EQUAL 0)
    ww_native_run_finish("execution timed out")
    message(FATAL_ERROR "Abort runtime suite execution timed out")
  endif()
  ww_native_run_execute("${case_name}" "${remaining}" "${ABORT_TEST_EXECUTABLE}" "${case_name}")
  if(NOT "${WW_RUN_CHILD_RESULT}" STREQUAL "1")
    ww_native_run_dump("${case_name}")
    ww_native_run_finish("execution failed: ${case_name}: ${WW_RUN_CHILD_RESULT}")
    message(FATAL_ERROR "abort case '${case_name}' did not exit through abortProgramNow(1).\nexpected result: 1\nactual result: ${WW_RUN_CHILD_RESULT}")
  endif()
  message(STATUS "abort case '${case_name}': exited 1 through abortProgramNow(1)")
endforeach()
ww_native_run_finish(passed)
