file(MAKE_DIRECTORY "${TEST_DIR}")
file(WRITE "${TEST_DIR}/empty" "")
# Exercise multiple encoder input chunks as well as a native runtime module.
string(REPEAT "WaterWall streaming encoder boundary fixture.\n" 10000 LARGE_INPUT)
file(WRITE "${TEST_DIR}/large" "${LARGE_INPUT}")
foreach(INPUT IN ITEMS "${MODULE}" "${TEST_DIR}/empty" "${TEST_DIR}/large")
  file(REMOVE "${TEST_DIR}/payload.xz" "${TEST_DIR}/repeat.xz")
  execute_process(COMMAND "${ENCODER}" "${INPUT}" "${TEST_DIR}/payload.xz" RESULT_VARIABLE RESULT)
  if(NOT RESULT EQUAL 0)
    message(FATAL_ERROR "Encoder failed: ${RESULT}")
  endif()
  execute_process(COMMAND "${ENCODER}" "${INPUT}" "${TEST_DIR}/repeat.xz" RESULT_VARIABLE RESULT)
  if(NOT RESULT EQUAL 0)
    message(FATAL_ERROR "Repeated encoding failed: ${RESULT}")
  endif()
  file(SHA256 "${TEST_DIR}/payload.xz" FIRST)
  file(SHA256 "${TEST_DIR}/repeat.xz" SECOND)
  if(NOT FIRST STREQUAL SECOND)
    message(FATAL_ERROR "Fixed encoder settings produced different bytes")
  endif()
  execute_process(COMMAND "${DECODER_TEST}" "${INPUT}" "${TEST_DIR}/payload.xz" RESULT_VARIABLE RESULT)
  if(NOT RESULT EQUAL 0)
    message(FATAL_ERROR "Decoder contract failed for ${INPUT}: ${RESULT}")
  endif()
  execute_process(COMMAND "${ENCODER}" "${INPUT}" "${TEST_DIR}/payload.xz"
    RESULT_VARIABLE RESULT OUTPUT_QUIET ERROR_QUIET)
  if(RESULT EQUAL 0)
    message(FATAL_ERROR "Encoder unexpectedly overwrote existing output")
  endif()
  file(SHA256 "${TEST_DIR}/payload.xz" AFTER)
  if(NOT FIRST STREQUAL AFTER)
    message(FATAL_ERROR "Failed invocation changed existing output")
  endif()
  # Opening input and output as the same file must not truncate the source.
  file(SHA256 "${INPUT}" INPUT_BEFORE)
  execute_process(COMMAND "${ENCODER}" "${INPUT}" "${INPUT}"
    RESULT_VARIABLE RESULT OUTPUT_QUIET ERROR_QUIET)
  file(SHA256 "${INPUT}" INPUT_AFTER)
  if(RESULT EQUAL 0 OR NOT INPUT_BEFORE STREQUAL INPUT_AFTER)
    message(FATAL_ERROR "Same-path encoding did not preserve its input")
  endif()
endforeach()
execute_process(COMMAND "${ENCODER}" "${TEST_DIR}/missing-input" "${TEST_DIR}/missing-output.xz"
  RESULT_VARIABLE RESULT OUTPUT_QUIET ERROR_QUIET)
if(RESULT EQUAL 0 OR EXISTS "${TEST_DIR}/missing-output.xz")
  message(FATAL_ERROR "Missing input did not fail cleanly")
endif()
